@baseUrl = http://localhost:3333
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc2Mzc2NWVjLTc3NjktNDg3Ny05ZDI5LTcyOTU2ZjBhNzM4MCIsImVtYWlsIjoic3Z2QHYuY29tIiwiaWF0IjoxNzA5MzgzODk4LCJleHAiOjE3MDkzODc0OTh9.Nw1iSnYKhR4gzWbcklC-9hoMgxPBHZfLzmFcAurXhu0

POST {{baseUrl}}/user
Content-Type: application/json

{
  "name":"Victor 3",
  "email":"sv3@g.com",
  "password":"12345"
}

###

POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email":"svv@v.com",
  "password":"1234"
}


###

GET {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

PUT {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email":"svv@v.com"
}

###

PATCH  {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "password":"12345",
  "newPassword":"1234"
}

###

POST {{baseUrl}}/question
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "question":"Como curtir a questão"
}

###

GET {{baseUrl}}/question/9e1177e3-a4ab-4ea9-8232-c49ea6f2c560
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

GET {{baseUrl}}/question/user
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

GET {{baseUrl}}/question/all
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

PUT {{baseUrl}}/question/9e1177e3-a4ab-4ea9-8232-c49ea6f2c560
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "question":"Como saber atualizar questão"
}
###

DELETE  {{baseUrl}}/question/b0e313e4-644f-434a-9eb7-9374c25a8ead
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

POST  {{baseUrl}}/like/question/b0e313e4-644f-434a-9eb7-9374c25a8ead
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

DELETE   {{baseUrl}}/like/7cc9f801-5af0-443c-9b95-8591bb0f6a15
Content-Type: application/json
Authorization: Bearer {{authToken}}
